### ISSUE TITLE
A user can add a recipe to their list of favourites.

### ISSUE THREAD

**Issue by mgatland** [girlcodeakl/girlcode2018-term2#52]
# Part 1 - Add to favourites

Take a look at feed2.html. There is a "next" link that shows the next post when you click on it.

Duplicate the link so there are two links. Make one say "Yes" and the other say "No".

The original "next" link was connected to a function. There is a line of code that makes the connection (near the end of the file, probably).

Duplicate the line of code that connects the link to the function.

Also duplicate the function that it points to.

Rename the duplicate copies so your 'Yes' button is connected to the new, duplicate function instead of the original.

To check the different functions are both working, add an alert popup inside each function.

Add this to one function:

```javascript
alert("function 1!");
```

Add this to the other function:

```javascript
alert("function 2! this is the other function!");
```

The alert command makes a message pop up. It's very annoying.

- [ ] You now have two links, "yes" and "no"
- [ ] clicking "yes" makes an annoying popup appear, then shows a new post
- [ ] clicking "no" makes a *different* annoying popup appear, then shows a new post

Once you're sure that's working, you should delete the alert commands because they are annoying.

# OK

so we have two different functions, both of them show the next post.

When you click yes, we still want to show the next post but we also want to tell the server that you *favourited* the current post.

When we tell the server to remember something, we use a *post* command. Add this code to that function:

```javascript
let data = {}
data.postId = $(".fixme").text();
$.post("/favourites", data);
```

There's a deliberate mistake in that code. We need to tell the server what post we are faving. To do that, we need to write down the post Id. We get that out of the web page using a selector. Where it says ".fixme", replace with the selector that selects the actual HTML element that contains the post Id....

- [ ] Use the network tab to check what is being sent to the server. You should see the post's ID number. If you haven't done this before, ask a mentor or someone on the team who has!

# ok

So now you have two buttons. When you click one of them, we tell the server to 'favourite' that post.

# The server side

Now we gotta tell the server how to understand your new command "/favourites". We're in the server now so open up *index.js*

- [ ] OK we opened up index.js

We need a library that remembers information for a particular user. Here's one we picked out earlier, install by running this command in the Command Prompt or Terminal:

```
npm install express-session
```

Now back in index.js, we add these lines near the top to get access to that new library, and set it up:

```javascript
let session = require('express-session');
app.use(session({ secret: 'girlcodesecret', cookie: { maxAge: 60000 }}));
```

> The secret should actually be secret, we're being a bit lax about security for now...

Express-session is a library that lets us store information in a "session", which is some storage related to a particular user. You can't see my session and I can't see your session. It's often used for shopping carts in online stores.

Now we need a function that tells our server how to react to the message from the client.

(You can add this anywhere that is *after* all the lines that start with "app.use")

```javascript
//when someone posts to favourites, run the 'addFavourite' function
app.post("/favourites", addFavourite);

function addFavourite(request, response) {
    let postId = "fixme";
   if (request.session.favourites === undefined) {
        request.session.favourites = []
   }
   request.session.favourites.push(postId);
   response.send("ok");
}
```

The code above has a deliberate mistake - you need to get the post Id out of the request. Have a look around index.js and you'll see lots of examples of how this is done...

To check if it's working, we need a way to view the list of favourites. Let's start with the most simple version possible by adding this to the server:

```javascript
//when someone gets favourites, run the 'getFavourites' function
app.get("/favourites", getFavourites);

function getFavourites(request, response) {
    response.send(request.session.favourites);
}
```

You can view the list of favourites (just their ids) by going to localhost:3000/favourites

Check:
- [ ] when the user clicks 'yes' that post is added to the favourites list.
- [ ] when the user clicks 'no' that post is *not* added to the favourites list.

# Make the server give you the actual posts instead of just their ids

Replace getFavourites with this:
```
function getFavourites(request, response) {
  if (request.session.favourites === undefined) {
    request.session.favourites = []
  }
  response.send(request.session.favourites.map(id => posts.find(post => post.id == id)));
}
```

# Make the main feed show your favourites instead of all posts

... where feed.html asks for "/posts", change it to ask for "/favourites"

**Comment by phailwhale** [comment]
feed page is now favourites
